name: CI and Deployment for Sui Move Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Sui Binaries
      run: |
        # Fetch the official Sui installer script and execute it.
        # This command downloads and runs the installer, adding 'sui' to the PATH.
        # The '-t' flag installs the toolchain only, '-y' enables non-interactive mode.
        # Always refer to official Sui documentation for the latest recommended installation method.
        curl -L https://github.com/MystenLabs/sui/releases/latest/download/sui-installer.sh | sh -s -- -y -t
        # Add Sui to PATH for subsequent steps in this job.
        # $HOME/.sui/bin is the typical location.
        echo "$HOME/.sui/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Installation
      run: |
        sui --version
        move --version # Verify Move CLI is also available (comes with Sui tools)
      shell: bash

    - name: Build Project (Also Fetches Dependencies)
      run: |
        # 'sui move build' compiles the Move package defined by Move.toml in the current directory.
        # It will also fetch dependencies if they are not already present.
        sui move build --path .
      shell: bash

    - name: Run Tests
      run: |
        # 'sui move test' compiles and runs tests defined in the package.
        sui move test --path .
      shell: bash

  deploy_to_testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: build # Ensures build job completes successfully first
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Example: Deploy only on push to main

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Sui Binaries
      run: |
        curl -L https://github.com/MystenLabs/sui/releases/latest/download/sui-installer.sh | sh -s -- -y -t
        echo "$HOME/.sui/bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure Sui Client for Deployment
      env:
        SUI_TESTNET_RPC_URL: ${{ secrets.SUI_TESTNET_RPC_URL }} # Optional: Specific RPC URL for testnet
        SUI_DEPLOYER_PRIVATE_KEY_BASE64: ${{ secrets.SUI_DEPLOYER_PRIVATE_KEY_BASE64 }} # Deployer's private key (base64 encoded)
        SUI_DEPLOYER_ALIAS: "testnet-deployer-ci" # Alias for the imported key
      run: |
        set -e # Exit immediately if a command exits with a non-zero status
        set -x # Echo each command before executing (for debugging)

        echo "Setting up Sui client for Testnet deployment..."
        # Ensure the .sui config directory exists
        mkdir -p $HOME/.sui/sui_config

        # Configure client to use a specific RPC endpoint for testnet if provided
        if [ -n "$SUI_TESTNET_RPC_URL" ]; then
          sui client new-env --alias ci-testnet --rpc "$SUI_TESTNET_RPC_URL"
          sui client switch --env ci-testnet
          echo "Switched to ci-testnet environment with RPC: $SUI_TESTNET_RPC_URL"
        else
          sui client switch --env testnet || echo "Warning: Failed to switch to default 'testnet' env. Using active env."
        fi

        echo "Importing private key..."
        # Ensure the SUI_DEPLOYER_PRIVATE_KEY_BASE64 secret is set
        if [ -z "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" ]; then
          echo "Error: SUI_DEPLOYER_PRIVATE_KEY_BASE64 secret not set."
          exit 1
        fi

        # Attempt to remove the alias first if it exists, to prevent import failure
        sui client remove-alias "$SUI_DEPLOYER_ALIAS" || echo "Alias $SUI_DEPLOYER_ALIAS did not exist or could not be removed, proceeding with import attempt."

        # Decode the key
        DECODED_KEY_HEX=$(echo "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" | base64 --decode | xxd -p -c 200)
        if [ -z "$DECODED_KEY_HEX" ]; then
           echo "Error: Decoding private key from base64 failed or resulted in empty key."
           exit 1
        fi
        echo "Private key decoded (hex representation will be used for import if sui client supports it, otherwise original pipe)."

        # Import the key.
        # The private key should be the raw key bytes (e.g., 32 bytes for ed25519), base64 encoded.
        # It should NOT be a mnemonic phrase.
        echo "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" | base64 --decode | sui client import-private-key --alias "$SUI_DEPLOYER_ALIAS"

        sui client switch --address "$SUI_DEPLOYER_ALIAS" # Set the imported key as active address
        echo "Switched active address to $SUI_DEPLOYER_ALIAS"

        echo "Verifying client configuration..."
        sui client active-env
        sui client active-address
        sui client gas --json # Verify gas objects for the active address
        echo "Sui client setup complete."
        set +x # Disable verbose output
      shell: bash

    - name: Deploy Contracts to Testnet
      env:
        SUI_TARGET_RPC_URL: ${{ secrets.SUI_TESTNET_RPC_URL }}
        SUI_DEPLOYER_ADDRESS_FOR_SCRIPT: ${{ env.SUI_DEPLOYER_ALIAS }}
        SUI_GAS_COIN_ID_FOR_SCRIPT: ${{ secrets.SUI_GAS_OBJECT_ID_TESTNET }}
      run: |
        chmod +x ./scripts/deploy.sh
        echo "Executing deploy.sh script..."
        echo "RPC URL for script (if used by deploy.sh): $SUI_TARGET_RPC_URL"
        echo "Deployer Alias for script (if used by deploy.sh): $SUI_DEPLOYER_ADDRESS_FOR_SCRIPT"
        echo "Gas Coin ID for script (if used by deploy.sh): $SUI_GAS_COIN_ID_FOR_SCRIPT"
        ./scripts/deploy.sh
      shell: bash
