name: CI and Deployment for Move Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Move Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl git
        wget https://move-language.github.io/move-cli/install.sh -O install-move.sh
        bash install-move.sh || { echo "Move CLI installation failed"; exit 1; }

    - name: Verify Move CLI Installation
      run: |
        if ! command -v move &> /dev/null; then
          echo "Move CLI is not installed. Exiting.";
          exit 1;
        fi
        move --version

    - name: Cache Move Build Directory
      uses: actions/cache@v3
      with:
        path: move_cache
        key: ${{ runner.os }}-move-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-move-

    - name: Install Dependencies
      run: |
        move build || { echo "Build failed. Check your Move code."; exit 1; }

    - name: Run Tests
      run: |
        move test || { echo "Tests failed. Fix failing test cases."; exit 1; }

  deploy:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Move Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl git
        wget https://move-language.github.io/move-cli/install.sh -O install-move.sh
        bash install-move.sh || { echo "Move CLI installation failed"; exit 1; }

    - name: Verify Move CLI Installation
      run: |
        if ! command -v move &> /dev/null; then
          echo "Move CLI is not installed. Exiting.";
          exit 1;
        fi
        move --version

    - name: Deploy Contracts
      run: |
        chmod +x ./scripts/deploy.sh
        ./scripts/deploy.sh || { echo "Deployment failed. Check the deployment script."; exit 1; }
