name: CI and Deployment for Sui Move Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # This will use the latest stable Rust (e.g., 1.80.0+)
        profile: minimal
        override: true

    - name: Install Sui Binaries using Cargo (Pinned Testnet Version)
      run: |
        set -e 
        set -x 

        echo "Installing Sui binaries using cargo with a pinned testnet tag..."
        # Using a specific, recent testnet tag for stability and compatibility.
        # Based on mainnet-v1.48.2, testnet-v1.48.1 is a strong candidate.
        # Always verify the chosen tag on https://github.com/MystenLabs/sui/releases
        SUI_RELEASE_TAG="testnet-v1.48.1" # <--- ### VERIFY THIS TAG IS SUITABLE ###
        
        cargo install --locked --git https://github.com/MystenLabs/sui.git --tag "$SUI_RELEASE_TAG" sui
        
        INSTALL_EXIT_CODE=$?
        if [ $INSTALL_EXIT_CODE -ne 0 ]; then
          echo "Error: cargo install for Sui (tag $SUI_RELEASE_TAG) failed with exit code $INSTALL_EXIT_CODE."
          echo "This might be due to the chosen Sui tag not being compatible with the current Rust stable version, or the tag not existing."
          echo "Please verify SUI_RELEASE_TAG is a recent and valid tag from https://github.com/MystenLabs/sui/releases"
          exit $INSTALL_EXIT_CODE
        fi
        echo "Successfully installed Sui from tag $SUI_RELEASE_TAG."

        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        set +x
      shell: bash

    - name: Verify Installation
      run: |
        sui --version
        sui move --version
      shell: bash

    - name: Build Project
      run: |
        sui move build --path .
      shell: bash

    - name: Run Tests
      run: |
        sui move test --path .
      shell: bash

  deploy_to_testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Sui Binaries using Cargo (Pinned Testnet Version)
      run: |
        set -e
        set -x
        echo "Installing Sui binaries using cargo with a pinned testnet tag for deployment..."
        # Ensure this tag MATCHES the tag used in the 'build' job for consistency.
        SUI_RELEASE_TAG="testnet-v1.48.1" # <--- ### VERIFY THIS TAG IS SUITABLE ###

        cargo install --locked --git https://github.com/MystenLabs/sui.git --tag "$SUI_RELEASE_TAG" sui
        
        INSTALL_EXIT_CODE=$?
        if [ $INSTALL_EXIT_CODE -ne 0 ]; then 
          echo "Error: cargo install for Sui (tag $SUI_RELEASE_TAG) failed with exit code $INSTALL_EXIT_CODE."
          exit $INSTALL_EXIT_CODE
        fi
        echo "Successfully installed Sui from tag $SUI_RELEASE_TAG for deployment."

        echo "$HOME/.
