name: CI and Deployment for Sui Move Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Sui Binaries
      run: |
        set -e # Exit immediately if a command exits with a non-zero status
        set -x # Echo each command before executing

        # Use the canonical URL for the Sui installation script from the main branch of the Sui repo
        SUI_INSTALLER_URL="https://raw.githubusercontent.com/MystenLabs/sui/main/scripts/install.sh"
        SUI_INSTALLER_SCRIPT="install-sui.sh" # Renamed for clarity

        echo "Downloading Sui installer from $SUI_INSTALLER_URL..."
        # Use -f to fail fast if the server returns an error (e.g., 404)
        # Use -s for silent mode, -S to show errors
        curl -fsSL "$SUI_INSTALLER_URL" -o "$SUI_INSTALLER_SCRIPT"
        CURL_EXIT_CODE=$?
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Error: curl failed to download Sui installer script with exit code $CURL_EXIT_CODE."
          exit $CURL_EXIT_CODE
        fi

        if [ ! -s "$SUI_INSTALLER_SCRIPT" ]; then # Check if file exists and is not empty
          echo "Error: Failed to download Sui installer script or downloaded file is empty."
          exit 1
        fi

        echo "First 5 lines of downloaded installer script:"
        head -n 5 "$SUI_INSTALLER_SCRIPT"
        echo "-------------------------------------------"

        echo "Making installer script executable..."
        chmod +x "$SUI_INSTALLER_SCRIPT"

        echo "Running Sui installer script..."
        # The script itself handles fetching appropriate binaries.
        # Common flags: --ci (for non-interactive CI environments), --toolchain-only (if you don't need a local network)
        # Consult the install.sh script or Sui docs for its specific flags.
        # Using --skip-prompts for non-interactive install.
        ./"$SUI_INSTALLER_SCRIPT" --skip-prompts --toolchain-only

        INSTALL_EXIT_CODE=$?
        if [ $INSTALL_EXIT_CODE -ne 0 ]; then
          echo "Error: Sui installer script failed with exit code $INSTALL_EXIT_CODE."
          exit $INSTALL_EXIT_CODE
        fi

        # Add Sui to PATH for subsequent steps in this job.
        # The install.sh script typically instructs to source a file or add to PATH.
        # Common location is $HOME/.sui/bin or $HOME/.cargo/bin if installed via cargo by the script.
        # The install.sh script from Sui repo usually updates .profile or .bashrc.
        # For CI, explicitly adding to GITHUB_PATH is more reliable.
        # Assuming the installer places binaries in $HOME/.sui/bin
        if [ -d "$HOME/.sui/bin" ]; then
          echo "Adding $HOME/.sui/bin to GITHUB_PATH"
          echo "$HOME/.sui/bin" >> $GITHUB_PATH
        elif [ -d "$HOME/.cargo/bin" ]; then # If installer used cargo install internally
          echo "Adding $HOME/.cargo/bin to GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        else
          echo "Warning: Sui binary directory not found at expected locations ($HOME/.sui/bin or $HOME/.cargo/bin)."
          echo "Sui CLI might not be in PATH."
        fi

        set +x
      shell: bash

    - name: Verify Installation
      run: |
        sui --version
        move --version 
      shell: bash

    - name: Build Project (Also Fetches Dependencies)
      run: |
        sui move build --path .
      shell: bash

    - name: Run Tests
      run: |
        sui move test --path .
      shell: bash

  deploy_to_testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: build 
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Sui Binaries
      run: |
        set -e
        set -x
        SUI_INSTALLER_URL="https://raw.githubusercontent.com/MystenLabs/sui/main/scripts/install.sh"
        SUI_INSTALLER_SCRIPT="install-sui.sh"
        curl -fsSL "$SUI_INSTALLER_URL" -o "$SUI_INSTALLER_SCRIPT"
        CURL_EXIT_CODE=$?
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Error: curl failed to download Sui installer script with exit code $CURL_EXIT_CODE."
          exit $CURL_EXIT_CODE
        fi
        if [ ! -s "$SUI_INSTALLER_SCRIPT" ]; then echo "Error: Installer script empty."; exit 1; fi
        echo "Head of installer:"
        head -n 5 "$SUI_INSTALLER_SCRIPT"
        chmod +x "$SUI_INSTALLER_SCRIPT"
        ./"$SUI_INSTALLER_SCRIPT" --skip-prompts --toolchain-only
        INSTALL_EXIT_CODE=$?
        if [ $INSTALL_EXIT_CODE -ne 0 ]; then echo "Installer script failed."; exit $INSTALL_EXIT_CODE; fi
        if [ -d "$HOME/.sui/bin" ]; then echo "$HOME/.sui/bin" >> $GITHUB_PATH;
        elif [ -d "$HOME/.cargo/bin" ]; then echo "$HOME/.cargo/bin" >> $GITHUB_PATH;
        else echo "Warning: Sui binary directory not found."; fi
        set +x
      shell: bash

    - name: Configure Sui Client for Deployment
      env:
        SUI_TESTNET_RPC_URL: ${{ secrets.SUI_TESTNET_RPC_URL }}
        SUI_DEPLOYER_PRIVATE_KEY_BASE64: ${{ secrets.SUI_DEPLOYER_PRIVATE_KEY_BASE64 }}
        SUI_DEPLOYER_ALIAS: "testnet-deployer-ci"
      run: |
        set -e 
        set -x 

        echo "Setting up Sui client for Testnet deployment..."
        mkdir -p $HOME/.sui/sui_config

        if [ -n "$SUI_TESTNET_RPC_URL" ]; then
          sui client new-env --alias ci-testnet --rpc "$SUI_TESTNET_RPC_URL"
          sui client switch --env ci-testnet
          echo "Switched to ci-testnet environment with RPC: $SUI_TESTNET_RPC_URL"
        else
          sui client switch --env testnet || echo "Warning: Failed to switch to default 'testnet' env. Using active env."
        fi

        echo "Importing private key..."
        if [ -z "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" ]; then
          echo "Error: SUI_DEPLOYER_PRIVATE_KEY_BASE64 secret not set."
          exit 1
        fi

        sui client remove-alias "$SUI_DEPLOYER_ALIAS" || echo "Alias $SUI_DEPLOYER_ALIAS did not exist or could not be removed."

        DECODED_KEY_HEX=$(echo "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" | base64 --decode | xxd -p -c 200)
        if [ -z "$DECODED_KEY_HEX" ]; then
           echo "Warning: Decoding private key from base64 resulted in empty or non-hex key for logging."
        fi
        echo "Private key decoded (hex representation for logging/debug: $DECODED_KEY_HEX)."

        echo "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" | base64 --decode | sui client import-private-key --alias "$SUI_DEPLOYER_ALIAS"

        sui client switch --address "$SUI_DEPLOYER_ALIAS" 
        echo "Switched active address to $SUI_DEPLOYER_ALIAS"

        echo "Verifying client configuration..."
        sui client active-env
        sui client active-address
        sui client gas --json 
        echo "Sui client setup complete."
        set +x 
      shell: bash

    - name: Deploy Contracts to Testnet
      env:
        SUI_TARGET_RPC_URL: ${{ secrets.SUI_TESTNET_RPC_URL }}
        SUI_DEPLOYER_ADDRESS_FOR_SCRIPT: ${{ env.SUI_DEPLOYER_ALIAS }} 
        SUI_GAS_COIN_ID_FOR_SCRIPT: ${{ secrets.SUI_GAS_OBJECT_ID_TESTNET }}
      run: |
        chmod +x ./scripts/deploy.sh
        echo "Executing deploy.sh script..."
        echo "RPC URL for script (if used by deploy.sh): $SUI_TARGET_RPC_URL"
        echo "Deployer Alias for script (if used by deploy.sh): $SUI_DEPLOYER_ADDRESS_FOR_SCRIPT"
        echo "Gas Coin ID for script (if used by deploy.sh): $SUI_GAS_COIN_ID_FOR_SCRIPT"
        ./scripts/deploy.sh
      shell: bash
