---
name: CI and Deployment for Sui Move Project

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test (Rust 1.86.0, Sui testnet-v1.48.1)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.86.0"
          profile: minimal
          override: true

      - name: Install Sui Binaries
        run: |
          set -e
          echo "Installing Sui binaries..."
          SUI_RELEASE_TAG="testnet-v1.48.1"
          cargo install --locked --git https://github.com/MystenLabs/sui.git --tag "$SUI_RELEASE_TAG" sui
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Verify Installation
        run: |
          rustc --version
          cargo --version
          sui --version
          sui move --version
        shell: bash

      - name: Build Project
        env:
          RUST_BACKTRACE: full
        run: |
          sui move build --path .
        shell: bash

      - name: Run Tests
        env:
          RUST_BACKTRACE: full
        run: |
          sui move test --path .
        shell: bash
