name: CI and Deployment for Sui Move Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable # Or a specific Rust version compatible with Sui
        profile: minimal
        override: true

    - name: Install Sui Binaries using Cargo
      run: |
        set -e # Exit immediately if a command exits with a non-zero status
        set -x # Echo each command before executing

        echo "Installing Sui binaries using cargo from testnet branch..."
        # Using '--branch testnet' for a more stable version than devnet.
        cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui
        
        INSTALL_EXIT_CODE=$?
        if [ $INSTALL_EXIT_CODE -ne 0 ]; then
          echo "Error: cargo install for Sui failed with exit code $INSTALL_EXIT_CODE."
          exit $INSTALL_EXIT_CODE
        fi

        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        set +x
      shell: bash

    # ... rest of your build job (Verify Installation, Build Project, Run Tests) ...
    # Ensure these steps are compatible with the chosen Sui version.

  deploy_to_testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Rust toolchain
      # ... (same as above) ...

    - name: Install Sui Binaries using Cargo
      run: |
        set -e
        set -x
        echo "Installing Sui binaries using cargo from testnet branch for deployment..."
        # Using '--branch testnet' for consistency with the build job.
        cargo install --locked --git https://github.com/MystenLabs/sui.git --branch testnet sui
        INSTALL_EXIT_CODE=$?
        if [ $INSTALL_EXIT_CODE -ne 0 ]; then echo "Error: cargo install for Sui failed."; exit $INSTALL_EXIT_CODE; fi
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        set +x
      shell: bash

    # ... rest of your deploy_to_testnet job (Configure Sui Client, Deploy Contracts) ...
