name: CI and Deployment for Move Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Move Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git
        curl -fsSL https://move-language.github.io/move-cli/install.sh | bash

    - name: Install Dependencies
      run: |
        move build

    - name: Run Tests
      run: |
        move test

  deploy:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Move Environment
      run: |
        curl -fsSL https://move-language.github.io/move-cli/install.sh | bash

    - name: Deploy Contracts
      run: |
        ./scripts/deploy.sh
