ame: CI and Deployment for Sui Move Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Sui Binaries
      run: |
        # Fetch the official Sui installer script and execute it.
        # This command downloads and runs the installer, adding 'sui' to the PATH.
        # The '-t' flag installs the toolchain only, '-y' enables non-interactive mode.
        # Always refer to official Sui documentation for the latest recommended installation method.
        curl -L https://github.com/MystenLabs/sui/releases/latest/download/sui-installer.sh | sh -s -- -y -t
        # Add Sui to PATH for subsequent steps in this job.
        # $HOME/.sui/bin is the typical location.
        echo "$HOME/.sui/bin" >> $GITHUB_PATH
      shell: bash

    - name: Verify Installation
      run: |
        sui --version
        move --version # Verify Move CLI is also available (comes with Sui tools)
      shell: bash

    - name: Build Project (Also Fetches Dependencies)
      run: |
        # 'sui move build' compiles the Move package defined by Move.toml in the current directory.
        # It will also fetch dependencies if they are not already present.
        sui move build --path .
      shell: bash

    - name: Run Tests
      run: |
        # 'sui move test' compiles and runs tests defined in the package.
        sui move test --path .
      shell: bash

  deploy_to_testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: build # Ensures build job completes successfully first
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Example: Deploy only on push to main

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Sui Binaries
      run: |
        curl -L https://github.com/MystenLabs/sui/releases/latest/download/sui-installer.sh | sh -s -- -y -t
        echo "$HOME/.sui/bin" >> $GITHUB_PATH
      shell: bash

    - name: Configure Sui Client for Deployment
      env:
        SUI_TESTNET_RPC_URL: ${{ secrets.SUI_TESTNET_RPC_URL }} # Optional: Specific RPC URL for testnet
        SUI_DEPLOYER_PRIVATE_KEY_BASE64: ${{ secrets.SUI_DEPLOYER_PRIVATE_KEY_BASE64 }} # Deployer's private key (base64 encoded)
        SUI_DEPLOYER_ALIAS: "testnet-deployer-ci" # Alias for the imported key
      run: |
        set -e # Exit immediately if a command exits with a non-zero status
        echo "Setting up Sui client for Testnet deployment..."
        # Ensure the .sui config directory exists
        mkdir -p $HOME/.sui/sui_config

        # Configure client to use a specific RPC endpoint for testnet if provided
        # Otherwise, it will use the default configured for 'testnet' or the active env.
        if [ -n "$SUI_TESTNET_RPC_URL" ]; then
          sui client new-env --alias ci-testnet --rpc "$SUI_TESTNET_RPC_URL"
          sui client switch --env ci-testnet
          echo "Switched to ci-testnet environment with RPC: $SUI_TESTNET_RPC_URL"
        else
          # Attempt to switch to a default testnet environment if RPC URL not provided
          # This assumes a 'testnet' env is already known or can be defaulted by 'sui client'
          sui client switch --env testnet || echo "Warning: Failed to switch to default 'testnet' env. Using active env."
        fi

        echo "Importing private key..."
        # Note: The SUI_DEPLOYER_PRIVATE_KEY_BASE64 secret should contain the base64 encoding
        # of the raw private key bytes (e.g., for ed25519, this is typically 32 bytes).
        # It should NOT be a mnemonic phrase for this command.
        if [ -n "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" ]; then
          # Attempt to remove the alias first if it exists, to prevent import failure
          sui client remove-alias "$SUI_DEPLOYER_ALIAS" || echo "Alias $SUI_DEPLOYER_ALIAS did not exist, proceeding with import."

          echo "$SUI_DEPLOYER_PRIVATE_KEY_BASE64" | base64 --decode | sui client import-private-key --alias "$SUI_DEPLOYER_ALIAS"
          sui client switch --address "$SUI_DEPLOYER_ALIAS" # Set the imported key as active address
          echo "Switched active address to $SUI_DEPLOYER_ALIAS"
        else
          echo "Error: SUI_DEPLOYER_PRIVATE_KEY_BASE64 secret not set."
          exit 1
        fi

        echo "Verifying client configuration..."
        sui client active-env
        sui client active-address
        sui client gas --json # Verify gas objects for the active address
        echo "Sui client setup complete."
      shell: bash

    - name: Deploy Contracts to Testnet
      env:
        # These environment variables are made available to the deploy.sh script.
        # The deploy.sh script would need to be written to utilize them if it needs
        # to override the active client configuration or requires them for other purposes.
        # For example, it could use SUI_TARGET_RPC_URL to pass --rpc-url to sui client commands.
        SUI_TARGET_RPC_URL: ${{ secrets.SUI_TESTNET_RPC_URL }} # Making RPC URL available to deploy.sh
        SUI_DEPLOYER_ADDRESS_FOR_SCRIPT: ${{ env.SUI_DEPLOYER_ALIAS }} # The alias of the active address
        SUI_GAS_COIN_ID_FOR_SCRIPT: ${{ secrets.SUI_GAS_OBJECT_ID_TESTNET }} # Specific gas coin for publish
        # Add any other environment variables your deploy.sh might need
      run: |
        chmod +x ./scripts/deploy.sh
        # The deploy.sh script should be written to use the configured Sui client environment
        # (active network, active address, and its gas objects) by default.
        # It can optionally use the environment variables above for more explicit control if designed to do so.
        # For instance, deploy.sh could check if SUI_GAS_COIN_ID_FOR_SCRIPT is set and use it with the --gas argument.
        echo "Executing deploy.sh script..."
        echo "RPC URL for script (if used): $SUI_TARGET_RPC_URL"
        echo "Deployer Alias for script (if used): $SUI_DEPLOYER_ADDRESS_FOR_SCRIPT"
        echo "Gas Coin ID for script (if used): $SUI_GAS_COIN_ID_FOR_SCRIPT"
        ./scripts/deploy.sh
      shell: bash
