---
name: Code Quality & Linting

"on":
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Rust toolchain setup removed - this is a Move-based project, not Rust
      # - name: Setup Rust toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     profile: minimal
      #     override: true
      #     components: rustfmt, clippy

      # Cargo formatting check removed - this is a Move-based project, not Rust
      # - name: Check code formatting
      #   run: |
      #     cargo fmt --all -- --check
      #   shell: bash

      # Cargo clippy check removed - this is a Move-based project, not Rust
      # - name: Run Clippy
      #   run: |
      #     cargo clippy --all-targets --all-features -- -D warnings
      #   shell: bash

      - name: Check for TODO/FIXME comments
        run: |
          echo "Checking for TODO/FIXME comments..."
          grep -r "TODO\|FIXME" --include="*.move" . || echo "No TODO/FIXME found"
        shell: bash
