---
name: Community Engagement & PR Automation

"on":
  issues:
    types: [opened, labeled, assigned]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  community-engagement:
    name: Community Engagement
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Welcome New Contributors
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            const isFirstTime = context.payload.sender.type !== 'User';
            if (!isFirstTime) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Welcome! Thank you for your contribution to the Governance System Enhancement Strategy.'
              });
            }

      - name: Label Management
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Managing labels for the contribution');

      - name: Auto-assign Reviewers
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Auto-assigning reviewers');

      - name: Update Project Board
        run: |
          echo "Updating project board status"
        shell: bash
