---
name: Performance Testing & Benchmarking

"on":
  push:
    branches: [ main ]
    paths:
      - '**.move'
  pull_request:
    branches: [ main ]
    paths:
      - '**.move'

jobs:
  performance-testing:
    name: Performance Benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Sui
        run: |
          cargo install --locked --git https://github.com/MystenLabs/sui.git sui
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Run Performance Tests
        run: |
          sui move test --path . --coverage
        shell: bash

      - name: Generate Performance Report
        run: |
          echo "Performance test completed"
          echo "Test results saved"
        shell: bash
